namespace BFM.Game.PersonEntity.Enums {
    public enum JobRole {
        Player,

        Chairman,
        Owner,
        ManagingDirector,
        Director,
        ManagerFirstTeam,
        HeadOfYouthDevelopment,
        AssistantManagerFirstTeam,
        CoachFirstTime,
        GkCoachFirstTeam,
        FitnessCoachFirstTeam,
        HeadPerformanceAnalyst,
        PerformanceAnalystFirstTeam,
        DirectorOfFootball,
        TechnicalDirector,
        ChiefScout,
        Scout,
        RecruitmentAnalyst,
        LoanManager,
        HeadPhysio,
        PhysioFirstTeam,
        ChiefDoctor,
        DoctorFirstTeam,
        ManagerThirdTeam,
        
        ManagerReserves,
        AssistantManagerReserves,
        CoachReserves,
        GkCoachReserves,
        FitnessCoachReserves,
        PerformanceAnalystReserves,
        PhysioReserves,
        SportsScientistReserves,
        DoctorReserves,
        
        AssistantManagerU23,
        CoachU23,
        GkCoachU23,
        FitnessCoachU23,
        PerformanceAnalystU23,
        PhysioU23,
        SportsScientistU23,
        DoctorU23,
        
        ManagerU23,
        AssistantManagerU18,
        CoachU18,
        GkCoachU18,
        FitnessCoachU18,
        PerformanceAnalystU18,
        PhysioU18,
        SportsScientistU18,
        DoctorU18,
        
    }
}
